### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by simplegoose** [Kidd254/Lawrence-s-Portfolio#5]
## Acknowledgements

- Correct git flow :heavy_check_mark: 
- No linter errors :heavy_check_mark: 

## Issues

- Kindly remove the hamburger menu on the desktop version since it will be of no use.
- Kindly add padding on the form input fields to match the design.
- Kindly make the about section to be responsive so that it can fit on various screen sizes.

**Comment by Kidd254** [comment]
i resolved the above issues, thanks for your contribution
