### ISSUE TITLE
Review coding for morning session with Lawrence: week 3 day 4

### ISSUE THREAD

**Issue by edahigure** [Kidd254/Lawrence-s-Portfolio#7]
#Highlights
Edahi (Master): 
Nice project. 

Nelson:
Recommendations:  

-Fix padding in some cards in the works section mobile.
-Check cards justify the content.

-Highlights: 	He has headings tags for different levels, Kind and good listener.

MOHAMED GAMIL ELDIMARDASH

-Great job on your project
-Placing every part in the right position
-Fonts and colors are well done

**Comment by Kidd254** [comment]
thanks for the feedback, i worked on the issues, and they are already resolved
